version: '3'

services:
  server:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.protocol=http"
      - "traefik.port=80"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:wall.codycolor.codemooc.net"
      - "traefik.frontend.redirect.entryPoint=https"
    restart: unless-stopped
